### ISSUE TITLE
!_debugDuringDeviceUpdate is not true

### ISSUE THREAD

**Issue by Technogeekpro** [SatYu26/Portfolio#2]
when I run the code i get this kind of error in console 
`======== Exception caught by scheduler library =====================================================
Assertion failed: file:///home/arbaz/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:311:12
!_debugDuringDeviceUpdate
is not true
====================================================================================================
Error: Assertion failed: file:///home/arbaz/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:311:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:41003/dart_sdk.js:5333:11)
    at Object.assertFailed (http://localhost:41003/dart_sdk.js:5269:15)
    at mouse_tracking.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:41003/packages/flutter/src/rendering/layer.dart.lib.js:5050:61)
    at http://localhost:41003/packages/flutter/src/rendering/layer.dart.lib.js:5108:33
    at mouse_tracking.MouseTracker.new.[_monitorMouseConnection] (http://localhost:41003/packages/flutter/src/rendering/layer.dart.lib.js:5045:7)
    at mouse_tracking.MouseTracker.new.updateWithEvent (http://localhost:41003/packages/flutter/src/rendering/layer.dart.lib.js:5107:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:41003/packages/flutter/src/rendering/layer.dart.lib.js:6081:46)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:41003/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:41003/packages/flutter/src/gestures/binding.dart.lib.js:258:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:41003/packages/flutter/src/gestures/binding.dart.lib.js:247:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:41003/packages/flutter/src/gestures/binding.dart.lib.js:237:65)
    at Object.invoke1 (http://localhost:41003/dart_sdk.js:183786:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:41003/dart_sdk.js:164268:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:41003/dart_sdk.js:164902:49)
    at http://localhost:41003/dart_sdk.js:165347:26
    at http://localhost:41003/dart_sdk.js:165312:16
    at http://localhost:41003/dart_sdk.js:165006:11

`

**Comment by SatYu26** [comment]
try downloading the latest code and update to latest flutter and the run the code and let me know
